### ISSUE TITLE
Toggle changing window scroll position

### ISSUE THREAD

**Issue by baroca** [sdrichter/QualityHighlighter#4]
When the list of entries is ordered alphabetically toggling the plugin will change the window position previously set.

To replicate, a large enough list of entries is necessary in order to the scroll bar be displayed.

Great plugin by the way!

Cheers

**Comment by sdrichter** [comment]
Hey there. Thanks for reporting the issue. I am unable to reproduce it on version 2.31 of KeePass2 on Ubuntu. What version of KeePass2 are you using? What platform are you running on?

**Comment by sdrichter** [comment]
Reproduced. Working on a fix.

**Comment by sdrichter** [comment]
This has been fixed on latest master commit.
