### ISSUE TITLE
Zero Bits = White/Clear?

### ISSUE THREAD

**Issue by WeaverThree** [sdrichter/QualityHighlighter#5]
Hey, one of the use cases I have for KeePass is keeping a folder of all my ssh public keys. Where there's a password associated with the related private key I store it too, but that's only about a third of them. The rest have zero bit, e.g., blank passwords. I think these should be treated differently than bad passwords, by e.g. not giving them a color at all perhaps.

**Comment by sdrichter** [comment]
Good suggestion. I will target it for next release.

**Comment by sdrichter** [comment]
Fixed by PR #6 .
